/*
    Tic-Tac-Toe web browser game
    Copyright (C) 2015 David Goffredo

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

(function() {
    var me = {};

    var MinimaxBook = (function() {
        var me = {}
        var book = {
            ".........": "X........",
            "........X": "....O...X",
            ".......X.": "......OX.",
            "......OXX": "O.....OXX",
            "......X..": "....O.X..",
            ".....X...": "...O.X...",
            ".....XOX.": "O....XOX.",
            "....O..XX": "....O.OXX",
            "....O.X.X": "....O.XOX",
            "....O.XX.": "....O.XXO",
            "....OX..X": "..O.OX..X",
            "....OXOXX": "..O.OXOXX",
            "....OXX..": ".O..OXX..",
            "....OXXOX": ".O..OXXOX",
            "....OXXXO": "O...OXXXO",
            "....X....": "O...X....",
            "....X.OX.": ".O..X.OX.",
            "...O.X..X": "..OO.X..X",
            "...O.X.X.": "..OO.X.X.",
            "...O.XX..": "..OO.XX..",
            "...OXX...": "O..OXX...",
            "...X.....": "O..X.....",
            "...X..OX.": ".O.X..OX.",
            "...XO...X": "O..XO...X",
            "...XO.OXX": "..OXO.OXX",
            "...XO.X..": "O..XO.X..",
            "...XO.XOX": ".O.XO.XOX",
            "...XO.XXO": "O..XO.XXO",
            "..O.OX.XX": "..O.OXOXX",
            "..O.OXX.X": "..O.OXXOX",
            "..OO.X.XX": "..OO.XOXX",
            "..OO.XX.X": "..OO.XXOX",
            "..OO.XXX.": "..OO.XXXO",
            "..OOXX..X": "O.OOXX..X",
            "..OOXX.X.": ".OOOXX.X.",
            "..OOXXOXX": "O.OOXXOXX",
            "..OOXXX..": "O.OOXXX..",
            "..OOXXXOX": "O.OOXXXOX",
            "..OOXXXXO": ".OOOXXXXO",
            "..OXOX..X": "O.OXOX..X",
            "..OXOXXOX": ".OOXOXXOX",
            "..X......": "..X.O....",
            "..X...OX.": "O.X...OX.",
            "..X.O...X": "..X.OO..X",
            "..X.O..X.": "..XOO..X.",
            "..X.O.OXX": "..X.OOOXX",
            "..X.O.X..": "..XOO.X..",
            "..X.O.XOX": ".OX.O.XOX",
            "..X.O.XXO": "O.X.O.XXO",
            "..X.OO.XX": "..XOOO.XX",
            "..X.OOX.X": "..XOOOX.X",
            "..X.OX...": "..X.OX..O",
            "..X.OX.XO": "O.X.OX.XO",
            "..X.OXX.O": "O.X.OXX.O",
            "..XO.X...": "..XO.X..O",
            "..XO.X.XO": "O.XO.X.XO",
            "..XO.XX.O": "..XOOXX.O",
            "..XOO..XX": "..XOOO.XX",
            "..XOO.X.X": "..XOOOX.X",
            "..XOO.XX.": "..XOOOXX.",
            "..XOOX.X.": "..XOOX.XO",
            "..XOOXX..": "..XOOXX.O",
            "..XOOXXXO": "O.XOOXXXO",
            "..XOXX..O": "..XOXXO.O",
            "..XOXXOXO": "O.XOXXOXO",
            "..XXO....": "O.XXO....",
            "..XXOO..X": "O.XXOO..X",
            "..XXOOOXX": "O.XXOOOXX",
            "..XXOX..O": "O.XXOX..O",
            ".O..OXX.X": ".O..OXXOX",
            ".O..OXXX.": ".O..OXXXO",
            ".O..X.OXX": "OO..X.OXX",
            ".O..XXOX.": ".O.OXXOX.",
            ".O.OXXOXX": "OO.OXXOXX",
            ".O.X..OXX": ".OOX..OXX",
            ".O.X.XOX.": ".O.XOXOX.",
            ".O.XOXOXX": ".OOXOXOXX",
            ".O.XOXX..": "OO.XOXX..",
            ".O.XOXXXO": "OO.XOXXXO",
            ".O.XX.OX.": ".O.XXOOX.",
            ".O.XXOOXX": "OO.XXOOXX",
            ".OOOXX.XX": "OOOOXX.XX",
            ".OOOXXXX.": "OOOOXXXX.",
            ".OOX.XOXX": "OOOX.XOXX",
            ".OOXX.OXX": "OOOXX.OXX",
            ".OX.OXX..": ".OX.OXXO.",
            ".OX.OXXXO": "OOX.OXXXO",
            ".OX.X.OX.": "OOX.X.OX.",
            ".OXOXXOX.": "OOXOXXOX.",
            ".OXX..OX.": ".OXXO.OX.",
            ".OXXO.OXX": ".OXXOOOXX",
            ".OXXOXOX.": ".OXXOXOXO",
            ".OXXXOOX.": "OOXXXOOX.",
            ".X.......": "OX.......",
            ".X....OX.": ".X..O.OX.",
            ".X..O...X": "OX..O...X",
            ".X..O.OXX": "OX..O.OXX",
            ".X..O.X..": "OX..O.X..",
            ".X..O.XOX": "OX..O.XOX",
            ".X..O.XXO": "OX..O.XXO",
            ".X..OXOX.": "OX..OXOX.",
            ".X.O.X...": ".XOO.X...",
            ".X.XO.OX.": "OX.XO.OX.",
            ".XO.OX..X": ".XO.OXO.X",
            ".XO.OXXOX": "OXO.OXXOX",
            ".XOO.X..X": ".XOO.XO.X",
            ".XOO.X.X.": ".XOOOX.X.",
            ".XOO.XOXX": "OXOO.XOXX",
            ".XOO.XX..": ".XOOOXX..",
            ".XOO.XXOX": "OXOO.XXOX",
            ".XOO.XXXO": ".XOOOXXXO",
            ".XOOOX.XX": ".XOOOXOXX",
            ".XOOOXX.X": ".XOOOXXOX",
            ".XOOOXXX.": ".XOOOXXXO",
            ".XOOXX...": ".XOOXX.O.",
            ".XOOXX.OX": "OXOOXX.OX",
            ".XOOXXO.X": "OXOOXXO.X",
            ".XOOXXXO.": "OXOOXXXO.",
            ".XX.O....": "OXX.O....",
            ".XX.O.OX.": "OXX.O.OX.",
            ".XX.OO..X": ".XXOOO..X",
            ".XX.OOOXX": ".XXOOOOXX",
            ".XX.OX..O": "OXX.OX..O",
            ".XXO.X..O": "OXXO.X..O",
            ".XXOO..X.": "OXXOO..X.",
            ".XXOO.X..": "OXXOO.X..",
            ".XXOOX.XO": "OXXOOX.XO",
            ".XXOOXX.O": "OXXOOXX.O",
            ".XXOXXO.O": "OXXOXXO.O",
            "O....XOXX": "O..O.XOXX",
            "O...X...X": "O...X.O.X",
            "O...X..X.": "OO..X..X.",
            "O...X.OXX": "O..OX.OXX",
            "O...X.X..": "O.O.X.X..",
            "O...XX...": "O..OXX...",
            "O...XXO.X": "O..OXXO.X",
            "O...XXOX.": "O..OXXOX.",
            "O..OXX..X": "O..OXXO.X",
            "O..OXX.X.": "O..OXXOX.",
            "O..OXXX..": "O.OOXXX..",
            "O..X....X": "O..XO...X",
            "O..X...X.": "O.OX...X.",
            "O..X..OXX": "O.OX..OXX",
            "O..X..X..": "OO.X..X..",
            "O..X.X...": "O..XOX...",
            "O..X.XOX.": "O..XOXOX.",
            "O..XO..XX": "O..XO.OXX",
            "O..XO.X.X": "O..XO.XOX",
            "O..XO.XX.": "O..XO.XXO",
            "O..XOX..X": "O.OXOX..X",
            "O..XOX.X.": "O..XOXOX.",
            "O..XOXOXX": "O.OXOXOXX",
            "O..XOXX..": "OO.XOXX..",
            "O..XOXXOX": "OO.XOXXOX",
            "O..XX....": "O..XXO...",
            "O..XX.O.X": "O..XXOO.X",
            "O..XXO..X": "O..XXOO.X",
            "O..XXO.X.": "OO.XXO.X.",
            "O..XXOOXX": "OO.XXOOXX",
            "O..XXOX..": "O.OXXOX..",
            "O.O.X.X.X": "OOO.X.X.X",
            "O.O.X.XX.": "OOO.X.XX.",
            "O.O.XXX..": "OOO.XXX..",
            "O.OOXX.XX": "O.OOXXOXX",
            "O.OOXXX.X": "OOOOXXX.X",
            "O.OOXXXX.": "OOOOXXXX.",
            "O.OX...XX": "O.OX..OXX",
            "O.OX..XX.": "OOOX..XX.",
            "O.OX.X.X.": "OOOX.X.X.",
            "O.OX.XOXX": "OOOX.XOXX",
            "O.OXOX.XX": "O.OXOXOXX",
            "O.OXOXX.X": "OOOXOXX.X",
            "O.OXX..X.": "OOOXX..X.",
            "O.OXX.OXX": "OOOXX.OXX",
            "O.OXX.X..": "OOOXX.X..",
            "O.OXXOX.X": "OOOXXOX.X",
            "O.OXXOXX.": "OOOXXOXX.",
            "O.X...OXX": "O.XO..OXX",
            "O.X..XOX.": "O.XO.XOX.",
            "O.X.X....": "O.X.X.O..",
            "O.X.X.O.X": "O.XOX.O.X",
            "O.X.X.OX.": "O.XOX.OX.",
            "O.X.XXO..": "O.XOXXO..",
            "O.XO.XXXO": "O.XOOXXXO",
            "O.XOXX...": "O.XOXXO..",
            "O.XOXX.XO": "O.XOXXOXO",
            "O.XX.....": "O.XXO....",
            "O.XX..OX.": "O.XXO.OX.",
            "O.XXO...X": "O.XXOO..X",
            "O.XXO..X.": "O.XXO..XO",
            "O.XXO.OXX": "O.XXOOOXX",
            "O.XXO.X..": "OOXXO.X..",
            "O.XXO.XOX": "OOXXO.XOX",
            "O.XXOO.XX": "O.XXOOOXX",
            "O.XXOOX.X": "O.XXOOXOX",
            "O.XXOX...": "O.XXOX..O",
            "O.XXOXOX.": "O.XXOXOXO",
            "O.XXX.O..": "O.XXXOO..",
            "O.XXXO...": "O.XXXOO..",
            "O.XXXOO.X": "OOXXXOO.X",
            "O.XXXOOX.": "OOXXXOOX.",
            "OO..X..XX": "OO..X.OXX",
            "OO..X.XX.": "OOO.X.XX.",
            "OO..XX.X.": "OO.OXX.X.",
            "OO..XXOXX": "OO.OXXOXX",
            "OO.OXX.XX": "OO.OXXOXX",
            "OO.OXXXX.": "OOOOXXXX.",
            "OO.X..X.X": "OO.X..XOX",
            "OO.X..XX.": "OOOX..XX.",
            "OO.X.XX..": "OO.XOXX..",
            "OO.X.XXOX": "OO.XOXXOX",
            "OO.XOXX.X": "OO.XOXXOX",
            "OO.XOXXX.": "OOOXOXXX.",
            "OO.XX..X.": "OOOXX..X.",
            "OO.XX.OXX": "OOOXX.OXX",
            "OO.XX.X..": "OOOXX.X..",
            "OO.XX.XOX": "OOOXX.XOX",
            "OO.XXO.XX": "OOOXXO.XX",
            "OO.XXOXX.": "OOOXXOXX.",
            "OOX.X..X.": "OOX.X.OX.",
            "OOX.X.OXX": "OOXOX.OXX",
            "OOX.XXOX.": "OOXOXXOX.",
            "OOXOXX.X.": "OOXOXXOX.",
            "OOXX..X..": "OOXXO.X..",
            "OOXX..XOX": "OOXXO.XOX",
            "OOXXO.X.X": "OOXXO.XOX",
            "OOXXO.XX.": "OOXXO.XXO",
            "OOXXOXX..": "OOXXOXXO.",
            "OOXXX.OX.": "OOXXXOOX.",
            "OOXXXO.X.": "OOXXXOOX.",
            "OX......X": "OX....O.X",
            "OX.....X.": "OX..O..X.",
            "OX....OXX": "OX.O..OXX",
            "OX....X..": "OX..O.X..",
            "OX...X...": "OX...XO..",
            "OX...XO.X": "OX.O.XO.X",
            "OX...XOX.": "OX.O.XOX.",
            "OX..O..XX": "OX..O.OXX",
            "OX..O.X.X": "OX..O.XOX",
            "OX..O.XX.": "OX..O.XXO",
            "OX..OX..X": "OXO.OX..X",
            "OX..OX.X.": "OX.OOX.X.",
            "OX..OXOXX": "OX.OOXOXX",
            "OX..OXX..": "OX..OXX.O",
            "OX..OXXOX": "OXO.OXXOX",
            "OX..X....": "OX..X..O.",
            "OX..X..OX": "OX.OX..OX",
            "OX..X.O.X": "OX.OX.O.X",
            "OX..X.XO.": "OXO.X.XO.",
            "OX..XX.O.": "OX.OXX.O.",
            "OX..XXO..": "OX.OXXO..",
            "OX.OOX.XX": "OX.OOXOXX",
            "OX.OOXXX.": "OX.OOXXXO",
            "OX.OX.XOX": "OXOOX.XOX",
            "OX.OXX...": "OX.OXXO..",
            "OX.OXX.OX": "OX.OXXOOX",
            "OX.OXXXO.": "OXOOXXXO.",
            "OX.X.....": "OX.XO....",
            "OX.X..O.X": "OX.XO.O.X",
            "OX.X.XO..": "OX.XOXO..",
            "OX.XO...X": "OX.XO.O.X",
            "OX.XO..X.": "OX.XO.OX.",
            "OX.XO.OXX": "OXOXO.OXX",
            "OX.XO.X..": "OX.XO.X.O",
            "OX.XO.XOX": "OXOXO.XOX",
            "OX.XOX...": "OX.XOXO..",
            "OX.XOXO.X": "OXOXOXO.X",
            "OX.XOXOX.": "OXOXOXOX.",
            "OX.XX..O.": "OX.XXO.O.",
            "OX.XXO...": "OX.XXO.O.",
            "OX.XXO.OX": "OX.XXOOOX",
            "OX.XXOO.X": "OX.XXOOOX",
            "OX.XXOXO.": "OXOXXOXO.",
            "OXO.OX.XX": "OXO.OXOXX",
            "OXO.OXX.X": "OXO.OXXOX",
            "OXO.X.X..": "OXO.X.XO.",
            "OXO.X.XOX": "OXOOX.XOX",
            "OXO.XXXO.": "OXOOXXXO.",
            "OXOOXX..X": "OXOOXXO.X",
            "OXOOXXX..": "OXOOXXXO.",
            "OXOX...X.": "OXOXO..X.",
            "OXOX..OXX": "OXOXO.OXX",
            "OXOXO..XX": "OXOXO.OXX",
            "OXOXO.XX.": "OXOXO.XXO",
            "OXOXOX..X": "OXOXOXO.X",
            "OXOXOX.X.": "OXOXOXOX.",
            "OXOXX.XO.": "OXOXXOXO.",
            "OXOXXOX..": "OXOXXOX.O",
            "OXX......": "OXXO.....",
            "OXX...O.X": "OXXO..O.X",
            "OXX...OX.": "OXXO..OX.",
            "OXX..XO..": "OXXO.XO..",
            "OXX.O...X": "OXX.OO..X",
            "OXX.O..X.": "OXXOO..X.",
            "OXX.O.OXX": "OXXOO.OXX",
            "OXX.O.X..": "OXXOO.X..",
            "OXX.O.XOX": "OXX.OOXOX",
            "OXX.OO.XX": "OXXOOO.XX",
            "OXX.OOX.X": "OXXOOOX.X",
            "OXX.OX...": "OXX.OX..O",
            "OXX.OXOX.": "OXXOOXOX.",
            "OXX.X..O.": "OXX.X.OO.",
            "OXX.X.O..": "OXXOX.O..",
            "OXX.X.OOX": "OXXOX.OOX",
            "OXX.XXOO.": "OXXOXXOO.",
            "OXXO....X": "OXXO..O.X",
            "OXXO...X.": "OXXO..OX.",
            "OXXO..X..": "OXXOO.X..",
            "OXXO.X...": "OXXO.XO..",
            "OXXO.X.XO": "OXXO.XOXO",
            "OXXO.XX.O": "OXXOOXX.O",
            "OXXOO..XX": "OXXOO.OXX",
            "OXXOO.X.X": "OXXOOOX.X",
            "OXXOO.XX.": "OXXOOOXX.",
            "OXXOOX.X.": "OXXOOXOX.",
            "OXXOOXX..": "OXXOOXX.O",
            "OXXOX....": "OXXOX.O..",
            "OXXOX..OX": "OXXOX.OOX",
            "OXXOXX..O": "OXXOXXO.O",
            "OXXOXX.O.": "OXXOXXOO.",
            "OXXXO....": "OXXXO...O",
            "OXXXO.O.X": "OXXXOOO.X",
            "OXXXO.OX.": "OXXXO.OXO",
            "OXXXOO..X": "OXXXOOO.X",
            "OXXXOXO..": "OXXXOXO.O",
            "OXXXX.OO.": "OXXXX.OOO",
            "OXXXXO.O.": "OXXXXOOO.",
            "OXXXXOO..": "OXXXXOOO.",
            "X........": "X...O....",
            "X.......O": "X.....X.O",
            "X......O.": "X.....XO.",
            "X.....O..": "XX....O..",
            "X.....OX.": "XO....OX.",
            "X.....XOO": "X..X..XOO",
            "X....O...": "X....OX..",
            "X....OX.O": "X..X.OX.O",
            "X....OXO.": "X..X.OXO.",
            "X...O....": "X..XO....",
            "X...O...X": "X..OO...X",
            "X...O..X.": "X..OO..X.",
            "X...O.OXX": "X..OO.OXX",
            "X...O.X..": "X..OO.X..",
            "X...O.X.O": "X..XO.X.O",
            "X...O.XO.": "X..XO.XO.",
            "X...O.XOX": "X..OO.XOX",
            "X...O.XXO": "X..OO.XXO",
            "X...OOX..": "X..XOOX..",
            "X...OX...": "XO..OX...",
            "X..O.....": "XX.O.....",
            "X..O..X.O": "X.XO..X.O",
            "X..O..XO.": "X..OX.XO.",
            "X..O.OX..": "X..OXOX..",
            "X..O.X...": "X.OO.X...",
            "X..OO..XX": "X..OO.OXX",
            "X..OO.X.X": "X..OO.XOX",
            "X..OO.XX.": "X..OOOXX.",
            "X..OOX..X": "X.OOOX..X",
            "X..OOX.X.": "X.OOOX.X.",
            "X..OOXOXX": "X.OOOXOXX",
            "X..OOXX..": "XO.OOXX..",
            "X..OOXXOX": "XO.OOXXOX",
            "X..OOXXXO": "XO.OOXXXO",
            "X..OX.XOO": "X.XOX.XOO",
            "X..OXOX.O": "X.XOXOX.O",
            "X..OXOXO.": "XX.OXOXO.",
            "X..XO....": "X..XO.O..",
            "X..XO...O": "X..XO.X.O",
            "X..XO..O.": "X..XO.XO.",
            "X..XO.O..": "X.XXO.O..",
            "X..XO.O.X": "XO.XO.O.X",
            "X..XO.OX.": "X.OXO.OX.",
            "X..XOO...": "X..XOOX..",
            "X..XOXO..": "XO.XOXO..",
            "X.O......": "X.OX.....",
            "X.O...X.O": "X.OX..X.O",
            "X.O...XO.": "X.OX..XO.",
            "X.O..OX..": "X.OX.OX..",
            "X.O.OX..X": "X.O.OXO.X",
            "X.O.OXXOX": "XOO.OXXOX",
            "X.OO.X..X": "X.OOOX..X",
            "X.OO.X.X.": "X.OOOX.X.",
            "X.OO.XOXX": "X.OOOXOXX",
            "X.OO.XX..": "X.OOOXX..",
            "X.OO.XXOX": "X.OOOXXOX",
            "X.OO.XXXO": "XOOO.XXXO",
            "X.OOOX.XX": "X.OOOXOXX",
            "X.OOOXX.X": "X.OOOXXOX",
            "X.OOOXXX.": "X.OOOXXXO",
            "X.OOX.XO.": "X.OOX.XOX",
            "X.OOXOX..": "X.OOXOX.X",
            "X.OOXX...": "X.OOXX..O",
            "X.OOXX.XO": "XOOOXX.XO",
            "X.OOXXX.O": "XOOOXXX.O",
            "X.OX....O": "X.OX..X.O",
            "X.OX...O.": "X.OX..XO.",
            "X.OX..O..": "X.OXX.O..",
            "X.OX.O...": "X.OX.OX..",
            "X.OXO....": "X.OXO.X..",
            "X.OXX.O.O": "X.OXXXO.O",
            "X.OXX.OO.": "X.OXXXOO.",
            "X.OXXOO..": "X.OXXOO.X",
            "X.X.O....": "XOX.O....",
            "X.X.OO..X": "X.XOOO..X",
            "X.X.OOOXX": "X.XOOOOXX",
            "X.X.OX..O": "XOX.OX..O",
            "X.XO..XOO": "XXXO..XOO",
            "X.XO.OX.O": "XXXO.OX.O",
            "X.XO.X..O": "XOXO.X..O",
            "X.XOO...X": "X.XOOO..X",
            "X.XOO..X.": "X.XOOO.X.",
            "X.XOO.OXX": "X.XOOOOXX",
            "X.XOO.X..": "XOXOO.X..",
            "X.XOO.X.O": "XXXOO.X.O",
            "X.XOO.XOX": "XOXOO.XOX",
            "X.XOO.XXO": "X.XOOOXXO",
            "X.XOOX.XO": "XOXOOX.XO",
            "X.XOOXX.O": "XOXOOXX.O",
            "X.XOXXO.O": "X.XOXXOOO",
            "X.XXO.O..": "XOXXO.O..",
            "X.XXO.O.O": "XXXXO.O.O",
            "X.XXO.OO.": "XXXXO.OO.",
            "X.XXOOO..": "XXXXOOO..",
            "XO.......": "XO.X.....",
            "XO....OXX": "XO..O.OXX",
            "XO....X.O": "XO.X..X.O",
            "XO....XO.": "XO.X..XO.",
            "XO...OX..": "XO.X.OX..",
            "XO...XOX.": "XO..OXOX.",
            "XO..OX..X": "XO..OX.OX",
            "XO..OX.X.": "XO..OXOX.",
            "XO..OXOXX": "XOO.OXOXX",
            "XO..OXX..": "XO..OXXO.",
            "XO..OXXXO": "XO.OOXXXO",
            "XO..X.OX.": "XO..X.OXO",
            "XO..XXOXO": "XO.OXXOXO",
            "XO.OOXX.X": "XO.OOXXOX",
            "XO.OOXXX.": "XO.OOXXXO",
            "XO.OX.XO.": "XOXOX.XO.",
            "XO.OXOX..": "XO.OXOXX.",
            "XO.OXOXXO": "XOXOXOXXO",
            "XO.OXXOX.": "XO.OXXOXO",
            "XO.X....O": "XO.X..X.O",
            "XO.X...O.": "XO.X..XO.",
            "XO.X..O..": "XO.XX.O..",
            "XO.X..OX.": "XO.XO.OX.",
            "XO.X.O...": "XO.X.OX..",
            "XO.XO....": "XO.XO.X..",
            "XO.XO.OXX": "XOOXO.OXX",
            "XO.XOX...": "XO.XOXO..",
            "XO.XOXO.X": "XO.XOXOOX",
            "XO.XOXOX.": "XOOXOXOX.",
            "XO.XX.O.O": "XO.XXXO.O",
            "XO.XX.OO.": "XO.XXXOO.",
            "XO.XX.OXO": "XO.XXOOXO",
            "XO.XXOO..": "XO.XXOO.X",
            "XO.XXOOX.": "XO.XXOOXO",
            "XOOOXOXX.": "XOOOXOXXX",
            "XOOOXX.X.": "XOOOXX.XO",
            "XOOX.....": "XOOX..X..",
            "XOOX..OXX": "XOOXO.OXX",
            "XOOXX.O..": "XOOXX.OX.",
            "XOOXX.OXO": "XOOXXXOXO",
            "XOOXXOOX.": "XOOXXOOXX",
            "XOX...OX.": "XOX.O.OX.",
            "XOX.O...X": "XOX.O..OX",
            "XOX.O..X.": "XOXOO..X.",
            "XOX.O.OXX": "XOX.OOOXX",
            "XOX.O.X..": "XOXOO.X..",
            "XOX.OX...": "XOX.OX.O.",
            "XOX.OX.XO": "XOXOOX.XO",
            "XOX.OXOX.": "XOX.OXOXO",
            "XOX.OXX.O": "XOX.OXXOO",
            "XOX.X.OXO": "XOXOX.OXO",
            "XOXO..X.O": "XOXOX.X.O",
            "XOXO.X.XO": "XOXO.XOXO",
            "XOXO.XX.O": "XOXOOXX.O",
            "XOXOO..XX": "XOXOOO.XX",
            "XOXOO.X.X": "XOXOO.XOX",
            "XOXOO.XX.": "XOXOOOXX.",
            "XOXOOX.X.": "XOXOOX.XO",
            "XOXOOXX..": "XOXOOXXO.",
            "XOXOXX..O": "XOXOXXO.O",
            "XOXXO....": "XOXXO..O.",
            "XOXXO.O..": "XOXXO.OX.",
            "XOXXO.O.X": "XOXXO.OOX",
            "XOXXO.OX.": "XOXXOOOX.",
            "XOXXO.OXO": "XOXXOXOXO",
            "XOXXOOOX.": "XOXXOOOXX",
            "XOXXOX..O": "XOXXOX.OO",
            "XOXXOXO..": "XOXXOXOO.",
            "XX....O.O": "XX....OXO",
            "XX....OO.": "XXX...OO.",
            "XX...OO..": "XX..XOO..",
            "XX...OOXO": "XX..XOOXO",
            "XX..O....": "XXO.O....",
            "XX..O.O..": "XXX.O.O..",
            "XX..O.OX.": "XXO.O.OX.",
            "XX..O.OXO": "XXX.O.OXO",
            "XX..XOO.O": "XX..XOOXO",
            "XX..XOOO.": "XXX.XOOO.",
            "XX.O....O": "XX.OX...O",
            "XX.O...O.": "XX.OX..O.",
            "XX.O..O..": "XX.OX.O..",
            "XX.O..OXO": "XX.OX.OXO",
            "XX.O.O...": "XX.OXO...",
            "XX.OO....": "XXXOO....",
            "XX.OO...X": "XXOOO...X",
            "XX.OO..X.": "XXOOO..X.",
            "XX.OO.OXX": "XXOOO.OXX",
            "XX.OO.X..": "XX.OOOX..",
            "XX.OO.XOX": "XX.OOOXOX",
            "XX.OO.XXO": "XX.OOOXXO",
            "XX.OX..OO": "XXXOX..OO",
            "XX.OX.O.O": "XX.OX.OXO",
            "XX.OX.OO.": "XXXOX.OO.",
            "XX.OXO..O": "XX.OXO.XO",
            "XX.OXO.O.": "XX.OXOXO.",
            "XX.OXOO..": "XX.OXOOX.",
            "XX.OXOXOO": "XXXOXOXOO",
            "XX.XO.O..": "XXOXO.O..",
            "XXO...O..": "XXO.X.O..",
            "XXO...OXO": "XXO.X.OXO",
            "XXO.O...X": "XXOOO...X",
            "XXO.O..X.": "XXOOO..X.",
            "XXO.O.X..": "XXOOO.X..",
            "XXO.OX...": "XXO.OXO..",
            "XXO.X.O.O": "XXO.X.OXO",
            "XXO.X.OO.": "XXO.X.OOX",
            "XXO.XOO..": "XXO.XOOX.",
            "XXOO.....": "XXOOX....",
            "XXOO.X...": "XXOOOX...",
            "XXOO.XO.X": "XXOOOXO.X",
            "XXOOO..XX": "XXOOO.OXX",
            "XXOOO.X.X": "XXOOOOX.X",
            "XXOOO.XX.": "XXOOOOXX.",
            "XXOOOX..X": "XXOOOXO.X",
            "XXOOOX.X.": "XXOOOXOX.",
            "XXOOOXX..": "XXOOOXXO.",
            "XXOOX...O": "XXOOX..XO",
            "XXOOX..O.": "XXOOX..OX",
            "XXOOX.O..": "XXOOX.OX.",
            "XXOOXO...": "XXOOXO.X.",
            "XXOOXOXO.": "XXOOXOXOX",
            "XXOOXX..O": "XXOOXX.OO",
            "XXOOXX.O.": "XXOOXX.OO",
            "XXOXO....": "XXOXO.O..",
        };
        me.book = book;
        return me;
    })();

    function getName() {
        return "minnie-max";
    }

    function getDisplayName() {
        return "Minnie Max";
    }

    function strForEach(s, func) {
        var length = s.length;
        for (var i = 0; i < length; ++i) {
            func(s[i], i, s);
        }
        return s;
    }

    var blankKeyChar = Core.blankKeyChar;

    function suggestMove(boardKey) {
        var moveKey = MinimaxBook.book[boardKey];
        assert(moveKey !== undefined);

        var move = {};
        strForEach(moveKey, function(ch, i) {
            if (boardKey[i] === blankKeyChar && ch !== blankKeyChar) {
                move.x = i % Core.dim;
                move.y = Math.floor(i / Core.dim);
            }
        });

        assert(move.x !== undefined && move.y !== undefined);
        return move;
    }

    function canCheat() {
        return false;
    }

    me.getName = getName;
    me.getDisplayName = getDisplayName;
    me.suggestMove = suggestMove;
    me.canCheat = canCheat;

    Ai.addEngine(me);
})();

